- hosts: localhost
  gather_facts: false
  vars:
    OSP_GUID: e9c2
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  gather_facts: false
  become: yes
  roles:
    - {name: osp-cluster, tag: osp-cluster}

- name: enable the load balancer tier
  gather_facts: false
  hosts: frontends
  become: yes
  roles:
    - {name: base-cfg , tag: base-cfg}
    - {name: loadbalancer-tier, tags: [loadbalancer, haproxy]}

- name: setup app tier
  gather_facts: false
  hosts: apps
  become: yes
  roles:
    - {name: base-cfg , tag: base-cfg}
    - {name: application-tier, tags: [application, tomcat]}

- name: setup database tier
  gather_facts: false
  hosts: appdbs
  become: yes
  roles:
    - {name: base-cfg , tag: base-cfg}
    - {name: postgres, tags: [db, postgres]}

- name: Ensure app is working
  gather_facts: false
  hosts: frontends
  become: yes
  roles:
    - {name: smoke-test, tags: smoke-test}
