- hosts: localhost
  vars:
    OSP_GUID: e9c2
  gather_facts: false
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - {name: aws-provision, tag: aws-provision}
