---
# tasks file for delete-osp-nodes
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
    loop: "{{result.ansible_facts.openstack_servers}}"
